### ISSUE TITLE
[공통] 개발초기세팅

### ISSUE THREAD

**Issue by 5o-hyun** [swyp-mema/mema-client#1]
### In Progress

>  개발 초기세팅 수정

- [x] 1. 각 운영체제에 따른 문서 끝 개행 처리
- [x] 2. 프리티어 세미콜론 true 
- [x] 3. 루트 레이아웃 추가 (자동)
- [x] 4. react undefined typescript-eslint 추가로 수정

**Comment by YerangPark** [comment]
Husky 패키지 설치하여 머릿말 체크하도록 했습니다. #4bce119
소현님이 이전에 전달주셨던 내용 중 이슈 넘버링 regex 옵션(subject-pattern)의 경우에는 지금 deprecated된 것인지 docs에 해당 항목이 없고, 추가 시 에러가 발생하여 제거했습니다. [commitlint Docs](https://commitlint.js.org/reference/rules.html)

**Comment by 5o-hyun** [comment]
확인했습니다.
초기세팅 개발이 완료되어 이슈를 종료합니다.
