### ISSUE TITLE
[공통] 디자인 시스템 및 공통 컴포넌트 구현

### ISSUE THREAD

**Issue by YerangPark** [swyp-mema/mema-client#2]
### 1. 디자인 시스템
- [x] 색상 팔레트
- [x] 타이포그래피
- [x] 아이콘

### 2. 공통 컴포넌트 구현
- [x] Button
- [x] Input
- [x] 상단 Nav Bar(Header)
- [x] 하단 Tab Bar
- [x] 모달창
- [x] 레이아웃

**Comment by 5o-hyun** [comment]
### 버튼 컴포넌트 개발
- 타입(3) : default, square, ghost
- 글씨(3) : bold(default), normal, thin

![버튼컴포넌트](https://github.com/user-attachments/assets/1779294d-9445-43b2-9d6c-a8b67a13309f)

### 사용 값
*name : 버튼이름 (require)
type : 버튼타입 (optional)
fontStyle : 글씨타입 (optional) 

### 사용 방법
`<Button name="버튼" />`
`<Button name="버튼" type="square" />`
`<Button name="버튼" type="ghost" fontStyle="normal" />`

**Comment by YerangPark** [comment]
## Input 공통 컴포넌트 개발
![image](https://github.com/user-attachments/assets/8b34fff7-b571-4ccc-94d0-36dd7ee65442)

기존에 개발했던 컴포넌트의 역할이 너무 커서 분리하는 작업을 통해 아래 컴포넌트로 분리함.
- `Input` : 인풋 기능만 담당
- `Label` : 상단 라벨
- `ErrorMessage` : 인풋 하단의 에러메세지
- `ToggleVisibilityButton` : 눈 아이콘 버튼
- `InputWrapper` : 인풋 관련 요소 래핑 및 하단 선 표시용

### 사용 방법
- 비밀번호 인풋 예시 (useInputState 커스텀 훅 이용)
```ts
const password = useInputState();
const [isPasswordVisible, setIsPasswordVisible] = useState(false);
//...
<InputWrapper isFocused={password.isFocused} isEmpty={password.isEmpty}>
  <Label isFocused={password.isFocused} isEmpty={password.isEmpty}>
    비밀번호
  </Label>
  <Input
    type={isPasswordVisible ? 'text' : 'password'}
    value={password.value}
    placeholder="비밀번호를 입력하세요"
    onChange={password.handleChange}
    onFocus={password.handleFocus}
    onBlur={password.handleBlur}
  />
  <ToggleVisibilityButton
    isVisible={isPasswordVisible}
    onClick={() => setIsPasswordVisible((prev) => !prev)}
  />
</InputWrapper>
```

### 추후 작업 예정
- 인증 요청 버튼이 포함된 Input 개발

**Comment by YerangPark** [comment]
# Modal 공통 컴포넌트 개발
Modal 컴포넌트 하나만으로 이용 가능하도록 타입을 정의했습니다.
그리고 사용될 텍스트를 미리 modalTypography.ts에 정의했습니다.

## 프로퍼티 설명
- `type` : Ok, OkCancel, Action (기본값은 Ok)
- `okButtonName` : (기본값 확인)
- `closeButtonName` : (기본값 취소)
- `actionButtonName` : 회색 글씨 버튼을 액션 버튼이라고 명명했어요.
- `onOk` : OK 버튼 콜백
- `onClose` : 취소 버튼 콜백
- `onAction` : 액션 버튼 콜백
- `width`
- `children`

## modalTypography 설명
![image](https://github.com/user-attachments/assets/52f733b2-0577-45d3-81f0-a8426d28a542)

## 타입별 예시
| 타입 | 예시 |
|-------|-------|
| Ok | <img src="https://github.com/user-attachments/assets/3affe4e7-3c8c-4b3a-bf97-1fe1444254bc" width="300"/> <img src="https://github.com/user-attachments/assets/95c551b3-9536-4b19-9c6d-963d178bd122" width="300"/> |
| OkCancel | <img src="https://github.com/user-attachments/assets/794812c0-27bf-4e6d-86a4-f2d0e36d59fa" width="300"/> |
| Action   | <img src="https://github.com/user-attachments/assets/58d853b2-3492-4252-ab28-952bb508f12e" width="300"/> |



### 타입별 사용 예시

**Ok 타입**
```tsx
import { Text, DisabledText, Emphasize, LargeText } from '@/components/Modal/modalTypography';
import Modal from '@/components/Modal';
// ...
<Modal type="Ok" onOk={handleConfirm} width="300px">
  <Text>
    이미 1개 이상의 미팅이 생성되었어요. <br />
    <Emphasize>참여코드</Emphasize> 메뉴를 통해 입장해주세요!
  </Text>
  <DisabledText>비회원은 1개의 모임만 생성이 가능해요</DisabledText>
</Modal>
```
``` tsx
<Modal type="Ok" onOk={handleConfirm} width="300px">
  <Text>
    참여코드 복사 완료!
    <br />
  </Text>
  <LargeText>1234</LargeText>
</Modal>
```


**OkCancel 타입**
```jsx
<Modal type="OkCancel" onOk={handleConfirm} onClose={handleConfirm} width="300px">
  <Text>정산을 공유하시겠어요?</Text>
</Modal>
```


**Action 타입**
```jsx
<Modal
  type="Action"
  onOk={handleConfirm}
  onAction={handleConfirm}
  width="300px"
  okButtonName="만날 장소 정하기"
  actionButtonName="홈으로"
>
  <Text>일정 선택이 완료되었어요!</Text>
</Modal>
```

**Comment by YerangPark** [comment]
하단 NavBar는 홈 UI 개발 시 구현하겠습니다

**Comment by 5o-hyun** [comment]
> 하단 NavBar는 홈 UI 개발 시 구현하겠습니다

넵
